apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hermes
  title: Hermes
  description: RMS Middleware Service
  annotations:
    backstage.io/source-location: url:https://git.taservs.net/rcom/hermes
    backstage.io/techdocs-ref: dir:.
    opsgenie.com/team: rms_incident_squad
  links:
    - url: https://teamcity.taservs.net/project/KubernetesServices_Rms_HermesV2?mode=builds
      title: Hermes Builds
    - url: https://git.taservs.net/ops/argo-apps/tree/master/rms/middleware/base/hermes
      title: Argo Apps
    - url: https://grafana-global.farm.va.main.ag1.axon.us/d/8fdf7b8e3/rms-incident-squad-dashboard
      title: RMS Incident Squad Grafana Dashboard
    - url: https://axon.quip.com/v0YUAbtjSIB1/RMS-Incident-Squad-On-Call-Runbook
      title: Incident On-call Runbook
    - url: https://axon.slack.com/archives/CN4QKSXB8
      title: IRS Slack Channel
spec:
  type: service
  owner: rms-incident-response-squad
  lifecycle: production
  dependsOn:
    - component:audit
    - component:blob
    - component:configsvc
    - component:zeke
    - component:rq
    - component:ugp
    - component:komrade
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  type: component
  name: hermes
  title: Iris
